### ISSUE TITLE
Add ?v=md5sum to JavaScript file links to ensure new versions are used instead of cached versions.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM_GUI_BUILDER#55]

**Comment by bmbroom** [comment]
Is this referring to links to the next/previous HTML pages?

(The links to javascript and other support files already have ?v=md5sum parameters.)

**Comment by jmelott** [comment]
When I had issues with one some of the files being cached in the GUI Builder, you made the comment above in a chain of emails between you, myself, and Chris, so I entered it as an issue so we'd have a reminder.
See email on 4/14/2023 @ 3:44 PM 
Titled:
Re: Major showstopper #41 still present
