### ISSUE TITLE
Map Build failure.  Possibly due to too many entries in discrete covariate.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM_GUI_BUILDER#59]
To reproduce:
Open GUI Builder.
Use Sample Matrix
Select "Show Advanced Features"
Select first column and row in matrix as covariates.
Select Color type for both as "Discrete"
Click Next twice to get to Cluster Matrix Page.

BUILD ERROR: Importing Heat Map Configuration Data. Index 99 out of bounds for length 99 Build error must be resolved to continue.

Errors in console:
080/NGCHM-web-builder/MapBuildDir/3728E3DE53FAFB0A0470074B67AF6E64/SampleMatrix/SampleMatrix.ngchm:1     Failed to load resource: the server responded with a status of 404 ()
ngchmWidget-min.js?v=2328b71125a2111f369d6eba960b24cc:913 Failed in call to get NGCHM from server: 404

**Comment by bmbroom** [comment]
I can't reproduce this.
